[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke test - basic functionality
    regression: Regression test - full feature test
    ui: UI test
addopts = 
    -v
    --strict-markers
    --tb=short
    --alluredir=reports/allure-results
    --capture=sys
console_output_style = progress

